contact_links:
  - name: Software Addition Request（ソフトウェア追加申請）
    url: https://docs.google.com/forms/d/e/1FAIpQLSfCxtIjG59kic5I1ue4bBMbDfcbvZzKAGVmP5JnXkH51binHw/viewform
    about: Not compatible with your software? Please contact us here!